import { z } from 'zod';
import {
  generateLinkedInPostOutputSchema,
  generateHooksOutputSchema,
  generateCtaOutputSchema,
  generateHashtagsOutputSchema,
  generateNetworkingMessageOutputSchema,
  generateLeadOutreachOutputSchema,
} from '@linkedin-growth/shared';
import { AIProvider } from './interface.js';

export class MockAIProvider implements AIProvider {
  name = 'mock';

  async generateText(prompt: string, systemPrompt?: string): Promise<string> {
    return `[AI Draft Generated by Mock Provider]\n\nReflecting on: "${prompt.slice(0, 80)}..."\n\nKey Takeaway: Focus on genuine engineering trade-offs, measurable metrics, and clean system design principles.`;
  }

  async generateStructured<T>(
    prompt: string,
    schema: z.ZodSchema<T>,
    systemPrompt?: string
  ): Promise<T> {
    const shape = (schema as any).shape || {};

    // 1. Hook Generation Schema
    if (shape.hooks || schema === (generateHooksOutputSchema as any)) {
      const topicMatch = prompt.match(/Topic:\s*([^\n]+)/i);
      const categoryMatch = prompt.match(/Category:\s*([^\n]+)/i);
      const topic = topicMatch ? topicMatch[1].trim() : 'technical trade-offs';
      const cat = categoryMatch ? categoryMatch[1].trim() : 'engineering';

      const mockHooks = {
        hooks: [
          `Most developers overlook this critical ${cat.toLowerCase().replace(/_/g, ' ')} detail until production breaks:`,
          `Stop treating ${topic} as an afterthought—here is the exact pattern that fixed our performance:`,
          `Why conventional wisdom about ${topic} is costing you hours of debugging:`,
          `3 hard-won engineering lessons from refactoring our ${topic} implementation:`,
          `A quick technical breakdown of what actually happens when you optimize ${topic}:`,
        ],
        rationale: 'Generated 5 grounded, curiosity-driven technical hooks based strictly on supplied context.',
      };
      return schema.parse(mockHooks);
    }

    // 2. CTA Generation Schema
    if (shape.ctas || schema === (generateCtaOutputSchema as any)) {
      const topicMatch = prompt.match(/Topic:\s*([^\n]+)/i);
      const topic = topicMatch ? topicMatch[1].trim() : 'this workflow';

      const mockCtas = {
        ctas: [
          `What is your go-to strategy when dealing with ${topic}? Let's discuss below!`,
          `Save this post if you're currently building or optimizing ${topic}.`,
          `Have you run into similar trade-offs in your stack? Drop your perspective in the comments.`,
        ],
      };
      return schema.parse(mockCtas);
    }

    // 3. Hashtag Suggestions Schema
    if ((shape.hashtags && !shape.hook) || schema === (generateHashtagsOutputSchema as any)) {
      const catMatch = prompt.match(/Category:\s*([^\n]+)/i);
      const category = catMatch ? catMatch[1].trim().toLowerCase() : 'software_engineering';

      const tagMap: Record<string, string[]> = {
        software_engineering: ['softwareengineering', 'programming', 'architecture', 'cleancode'],
        ai: ['artificialintelligence', 'machinelearning', 'llm', 'softwareengineering'],
        web_development: ['react', 'typescript', 'frontend', 'webdev'],
        linux: ['linux', 'terminal', 'devops', 'sysadmin'],
        databases: ['postgresql', 'databases', 'systemdesign', 'sql'],
        cloud: ['docker', 'cloud', 'devops', 'kubernetes'],
        dev_tools: ['devtools', 'productivity', 'typescript', 'backend'],
        dsa: ['algorithms', 'datastructures', 'leetcode', 'computerscience'],
        career: ['careers', 'internships', 'softwareengineer', 'learning'],
      };

      const tags = tagMap[category] || ['softwareengineering', 'typescript', 'programming', 'buildinpublic'];
      return schema.parse({ hashtags: tags });
    }

    // 4. Networking Outreach Schema
    if (
      shape.messageDraft ||
      (shape.message && !shape.fullDraft && !shape.closingQuestion) ||
      schema === (generateNetworkingMessageOutputSchema as any)
    ) {
      const nameMatch = prompt.match(/Name:\s*([^\n]+)/i);
      const roleMatch = prompt.match(/Role:\s*([^\n]+)/i);
      const compMatch = prompt.match(/Company:\s*([^\n]+)/i);
      const relMatch = prompt.match(/Relevance Reason:\s*([^\n]+)/i);

      const name = nameMatch ? nameMatch[1].replace(/\(DEMO\)/g, '').trim() : 'there';
      const role = roleMatch && roleMatch[1].trim() !== 'None' && roleMatch[1].trim() !== 'undefined' ? roleMatch[1].trim() : null;
      const company = compMatch && compMatch[1].trim() !== 'None' && compMatch[1].trim() !== 'undefined' ? compMatch[1].trim() : null;
      const relevance = relMatch && relMatch[1].trim() !== 'None' && relMatch[1].trim() !== 'undefined' ? relMatch[1].trim() : null;

      const basis: string[] = [];
      if (name && name !== 'there') basis.push('Name');
      if (role) basis.push('Role');
      if (company) basis.push('Company');
      if (relevance) basis.push('RelevanceReason');

      const isLimited = basis.length <= 1;

      let message = '';
      if (!isLimited && role && company && relevance) {
        message = `Hi ${name}, I came across your work as ${role} at ${company}. Specifically noted: "${relevance.slice(0, 100)}". As a CS student building systems and web tools, I would love to connect and follow your work!`;
      } else if (!isLimited && role && company) {
        message = `Hi ${name}, I came across your work as ${role} at ${company}. As a CS student focusing on full-stack systems and developer tooling, I'd love to connect and stay in touch!`;
      } else if (!isLimited && company) {
        message = `Hi ${name}, noticed the impressive work coming out of ${company}. As a software engineering student, I'd love to connect and follow updates!`;
      } else {
        message = `Hi ${name}, I came across your engineering profile while researching modern tech stacks. As a CS student building web systems, I'd love to connect and follow your updates!`;
      }

      const mockResult = {
        message,
        messageDraft: message,
        personalizationBasis: basis,
        isLimitedPersonalization: isLimited,
        toneNotes: isLimited
          ? 'Personalization data is limited. Draft is professional and concise.'
          : `Personalized using verified ${basis.join(', ')}. Authentic and concise.`,
      };
      return schema.parse(mockResult);
    }

    // 5. Lead Outreach Schema
    if (
      shape.problemStatement ||
      shape.closingQuestion ||
      shape.fullDraft ||
      schema === (generateLeadOutreachOutputSchema as any)
    ) {
      const compMatch = prompt.match(/Company:\s*([^\n]+)/i);
      const nameMatch = prompt.match(/Contact Name:\s*([^\n]+)/i);
      const webMatch = prompt.match(/Website:\s*([^\n]+)/i);
      const probMatch = prompt.match(/Observed Problem:\s*([^\n]+)/i);
      const oppMatch = prompt.match(/Opportunity:\s*([^\n]+)/i);

      const company = compMatch ? compMatch[1].replace(/\(DEMO\)/g, '').trim() : 'your company';
      const contactName = nameMatch && nameMatch[1].trim() !== 'None' && !nameMatch[1].includes('Founder /') ? nameMatch[1].trim() : '';
      const website = webMatch ? webMatch[1].trim() : '';
      const problem = probMatch ? probMatch[1].trim() : 'mobile checkout latency and layout shifts';
      const opportunity = oppMatch ? oppMatch[1].trim() : 'modern frontend redesign with sub-second page transitions';

      const greeting = contactName ? `Hi ${contactName}` : 'Hi there';

      const personalizationBasis: string[] = [];
      if (company && company !== 'your company') personalizationBasis.push(`Company: ${company}`);
      if (contactName) personalizationBasis.push(`Contact: ${contactName}`);
      if (website) personalizationBasis.push(`Website: ${website}`);
      if (problem) personalizationBasis.push(`Observed Problem: ${problem.slice(0, 80)}`);
      if (opportunity) personalizationBasis.push(`Opportunity: ${opportunity.slice(0, 80)}`);

      const observation = `I noticed ${company}'s website (${website || 'storefront'}) has ${problem.slice(0, 90)}.`;
      const problemStatement = `This increases friction for users and directly impacts conversion rates.`;
      const valueProposition = `A focused implementation around ${opportunity.slice(0, 100)} can resolve this with measurable speed gains.`;
      const closingQuestion = `Would you be open to a quick 3-minute Loom video breaking down 3 specific fixes?`;

      const connectionBody = `${greeting}, noticed ${company}'s site while auditing web performance. Spotted a quick fix for ${problem.slice(0, 60)}. Would love to connect!`;
      const shortBody = `${greeting},\n\nI was analyzing ${company}'s site and noticed ${problem.slice(0, 90)}.\n\nWe recently tackled a similar bottleneck using ${opportunity.slice(0, 70)}.\n\nWould you be open to a 3-minute video breakdown of 3 quick fixes?`;
      const detailedBody = `${greeting},\n\nI was reviewing ${company}'s website (${website}) earlier today and noticed ${problem}.\n\nThis introduces friction right in the user experience and impacts conversion clarity.\n\n${opportunity}.\n\nWould you be open to a quick 3-minute Loom video walking through 3 specific high-impact fixes you can implement right away?`;

      const variants = [
        {
          type: 'CONNECTION' as const,
          body: connectionBody,
          personalizationBasis,
          status: 'DRAFT' as const,
          createdAt: new Date().toISOString(),
        },
        {
          type: 'SHORT' as const,
          body: shortBody,
          personalizationBasis,
          status: 'DRAFT' as const,
          createdAt: new Date().toISOString(),
        },
        {
          type: 'DETAILED' as const,
          body: detailedBody,
          personalizationBasis,
          status: 'DRAFT' as const,
          createdAt: new Date().toISOString(),
        },
      ];

      const mockResult = {
        observation,
        problemStatement,
        valueProposition,
        closingQuestion,
        fullDraft: detailedBody,
        personalizationBasis,
        variants,
        isLimitedPersonalization: personalizationBasis.length < 2,
        warnings: personalizationBasis.length < 2 ? ['Limited verified observations — review carefully before sending.'] : [],
      };
      return schema.parse(mockResult);
    }

    // 6. LinkedIn Post Generation (Content Post / default)
    const ideaMatch = prompt.match(/Idea:\s*([^\n]+)/i);
    const topicMatch = prompt.match(/Topic:\s*([^\n]+)/i);
    const catMatch = prompt.match(/Category:\s*([^\n]+)/i);
    const lessonMatch = prompt.match(/Main Lesson[^:]*:\s*([^\n]+)/i);
    const contextMatch = prompt.match(/Source Context:\s*([^\n]+)/i);
    const lengthMatch = prompt.match(/Length:\s*([^\n]+)/i);

    const rawTopic = (ideaMatch ? ideaMatch[1] : topicMatch ? topicMatch[1] : '').trim();
    const rawCategory = (catMatch ? catMatch[1] : 'SOFTWARE_ENGINEERING').trim();
    const rawLesson = (lessonMatch ? lessonMatch[1] : '').trim();
    const rawContext = (contextMatch ? contextMatch[1] : '').trim();
    const length = (lengthMatch ? lengthMatch[1].toUpperCase() : 'MEDIUM').trim();

    const basis: string[] = [];
    if (rawTopic) basis.push('Topic/Idea');
    if (rawLesson) basis.push('Lesson');
    if (rawContext) basis.push('SourceContext');
    if (rawCategory) basis.push('Category');

    const isLimited = (rawTopic.length < 20 && rawContext.length < 20 && rawLesson.length < 20);
    const warnings: string[] = [];
    if (isLimited) {
      warnings.push('Limited context — verify factual claims before publishing.');
    }

    const displayTopic = rawTopic || 'Practical Engineering Trade-offs';
    const cleanTitle = displayTopic.length > 60 ? `${displayTopic.slice(0, 57)}...` : displayTopic;

    let bodyContent = '';
    if (length === 'SHORT') {
      bodyContent = `When working with ${displayTopic}, the biggest pitfall is premature optimization without measuring.\n\n3 key takeaways:\n1. Profile before refactoring.\n2. Keep data flows unidirectional and simple.\n3. Measure p99 latency under load.\n\nFocus on reliability first.`;
    } else if (length === 'LONG') {
      bodyContent = `Here is a deep dive into what we learned building and profiling ${displayTopic}:\n\n1. The Problem Setup:\nNaive implementations frequently cause unintended resource leaks and cascading latency spikes during concurrent loads.\n\n2. Key Architectural Decisions:\n- Isolated state transformations using pure functions\n- Explicit backpressure control on data pipelines\n- Automated regression tests for memory boundaries\n\n3. The Measurable Result:\nReduced peak memory by over 50% and eliminated OOM errors entirely across all benchmark suites.\n\n4. What We Would Do Differently:\nInvest in deterministic schema validations earlier in the lifecycle to avoid manual payload validation overhead.\n\nEngineering is all about balancing simplicity against performance.`;
    } else {
      bodyContent = `Here is a practical breakdown of how we approached ${displayTopic}:\n\n1. Identify bottlenecks using structured profiling rather than guesswork.\n2. Replace monolithic allocations with streaming transformations.\n3. Validate boundary states and error recovery at each layer.\n\nThe result? A rock-solid, maintainable architecture with zero unhandled edge cases under production load.`;
    }

    const mockResult = {
      title: cleanTitle,
      hook: `Most developers treat ${displayTopic.toLowerCase()} as straightforward until edge cases strike. Here is what we learned: 👇`,
      body: bodyContent,
      cta: `How do you approach ${displayTopic.toLowerCase()} in your own projects? Let's discuss in the comments!`,
      hashtags: ['softwareengineering', 'backend', 'typescript', 'architecture'],
      suggestedHashtags: ['softwareengineering', 'backend', 'typescript', 'architecture'],
      alternativeHooks: [
        `Why naive approaches to ${displayTopic.toLowerCase()} cause silent failures:`,
        `3 production lessons on optimizing ${displayTopic.toLowerCase()} without complex dependencies:`,
        `What every engineer should know before refactoring ${displayTopic.toLowerCase()}:`,
      ],
      personalizationBasis: basis,
      isLimitedContext: isLimited,
      warnings,
    };

    return schema.parse(mockResult);
  }

  async analyze(input: string, context?: string): Promise<{ summary: string; insights: string[] }> {
    return {
      summary: `Analyzed input (${input.length} characters) in context of ${context || 'general technical analysis'}.`,
      insights: [
        'High technical relevance observed',
        'Clean structure suitable for actionable outreach or content generation',
      ],
    };
  }

  async summarize(text: string, maxWords: number = 50): Promise<string> {
    const words = text.split(/\s+/).slice(0, maxWords).join(' ');
    return `${words}${text.split(/\s+/).length > maxWords ? '...' : ''}`;
  }
}
