export enum NetworkingStatus {
  DISCOVERED = 'DISCOVERED',
  REVIEWING = 'REVIEWING',
  APPROVED = 'APPROVED',
  CONTACTED = 'CONTACTED',
  REPLIED = 'REPLIED',
  FOLLOW_UP = 'FOLLOW_UP',
  CONNECTED = 'CONNECTED',
  ARCHIVED = 'ARCHIVED',
}

export enum ContactCategory {
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  AI_ENGINEER = 'AI_ENGINEER',
  FOUNDER = 'FOUNDER',
  RECRUITER = 'RECRUITER',
  HIRING_MANAGER = 'HIRING_MANAGER',
  DESIGNER = 'DESIGNER',
  CREATOR = 'CREATOR',
  OTHER = 'OTHER',
}

export enum NetworkingMessageType {
  CONNECTION_REQUEST = 'CONNECTION_REQUEST',
  FOLLOW_UP = 'FOLLOW_UP',
  GENERAL = 'GENERAL',
}

export enum NetworkingMessageStatus {
  DRAFT = 'DRAFT',
  USED = 'USED',
  ARCHIVED = 'ARCHIVED',
}

export enum ContentStatus {
  IDEA = 'IDEA',
  DRAFT = 'DRAFT',
  REVIEW = 'REVIEW',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum ContentCategory {
  SOFTWARE_ENGINEERING = 'SOFTWARE_ENGINEERING',
  AI = 'AI',
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  LINUX = 'LINUX',
  DSA = 'DSA',
  PROJECT_BUILDING = 'PROJECT_BUILDING',
  OPEN_SOURCE = 'OPEN_SOURCE',
  CAREER = 'CAREER',
  LEARNING = 'LEARNING',
  INTERNSHIP = 'INTERNSHIP',
  CLOUD = 'CLOUD',
  DATABASES = 'DATABASES',
  DEV_TOOLS = 'DEV_TOOLS',
  ENGINEERING_INSIGHTS = 'ENGINEERING_INSIGHTS',
  PERSONAL_PROJECT = 'PERSONAL_PROJECT',
  OTHER = 'OTHER',
}

export enum ContentLength {
  SHORT = 'SHORT',
  MEDIUM = 'MEDIUM',
  LONG = 'LONG',
}

export enum LeadStatus {
  DISCOVERED = 'DISCOVERED',
  RESEARCHING = 'RESEARCHING',
  QUALIFIED = 'QUALIFIED',
  OUTREACH_DRAFT = 'OUTREACH_DRAFT',
  CONTACTED = 'CONTACTED',
  REPLIED = 'REPLIED',
  MEETING = 'MEETING',
  PROPOSAL = 'PROPOSAL',
  WON = 'WON',
  LOST = 'LOST',
  ARCHIVED = 'ARCHIVED',
}

export enum InternshipStatus {
  NEW = 'NEW',
  REVIEWING = 'REVIEWING',
  SAVED = 'SAVED',
  INTERESTED = 'INTERESTED',
  CLOSED = 'CLOSED',
  EXPIRED = 'EXPIRED',
}

export enum TaskType {
  NETWORKING = 'NETWORKING',
  CONTENT = 'CONTENT',
  LEAD = 'LEAD',
  INTERNSHIP = 'INTERNSHIP',
  ANALYTICS = 'ANALYTICS',
  GENERAL = 'GENERAL',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
  DISMISSED = 'DISMISSED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum NotificationType {
  NEW_INTERNSHIP = 'NEW_INTERNSHIP',
  FOLLOW_UP_DUE = 'FOLLOW_UP_DUE',
  CONTENT_REVIEW = 'CONTENT_REVIEW',
  CONTENT_SCHEDULED = 'CONTENT_SCHEDULED',
  CONTENT_PUBLISH_REMINDER = 'CONTENT_PUBLISH_REMINDER',
  CONTENT_METRICS_DUE = 'CONTENT_METRICS_DUE',
  LEAD_FOUND = 'LEAD_FOUND',
  LEAD_FOLLOW_UP = 'LEAD_FOLLOW_UP',
  ANALYTICS_UPDATE = 'ANALYTICS_UPDATE',
}

export enum AnalyticsPeriod {
  SEVEN_DAYS = '7d',
  THIRTY_DAYS = '30d',
  NINETY_DAYS = '90d',
  ONE_YEAR = '1y',
  CUSTOM = 'custom',
}

export enum AnalyticsGroupBy {
  DAY = 'day',
  WEEK = 'week',
  MONTH = 'month',
}

